// 🛸 ORBIT Flight Plan
// Implementation planning and GitHub issue generation

import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { join } from 'path';
import { appendLog } from '../core/index.js';
import { printSection, printSuccess, printError, colors } from '../utils/output.js';
import { commandExists, execQuiet } from '../utils/exec.js';

const PLANS_DIR = '.copilot/plans';

export interface FlightPlanOptions {
  depth?: 1 | 2 | 3;
  dryRun?: boolean;
  noIssues?: boolean;
}

export interface FlightPlan {
  id: string;
  title: string;
  objective: string;
  status: 'draft' | 'issues_created' | 'in_progress' | 'complete' | 'failed';
  createdAt: string;
  phases: FlightPlanPhase[];
}

export interface FlightPlanPhase {
  name: string;
  tasks: FlightPlanTask[];
}

export interface FlightPlanTask {
  id: string;
  description: string;
  completed: boolean;
  issueNumber?: number;
}

export class FlightPlanGenerator {
  private options: FlightPlanOptions;

  constructor(options: FlightPlanOptions = {}) {
    this.options = {
      depth: options.depth || 2,
      dryRun: options.dryRun || false,
      noIssues: options.noIssues || false
    };
    this.ensureDir();
  }

  private ensureDir(): void {
    if (!existsSync(PLANS_DIR)) {
      mkdirSync(PLANS_DIR, { recursive: true });
    }
  }

  generatePlanId(): string {
    const files = existsSync(PLANS_DIR) ? readdirSync(PLANS_DIR).filter(f => f.endsWith('.md')) : [];
    return `plan-${String(files.length + 1).padStart(3, '0')}`;
  }

  async createPlan(feature: string): Promise<string> {
    const planId = this.generatePlanId();
    const planFile = join(PLANS_DIR, `${planId}.md`);

    console.log(colors.primary(`
╔══════════════════════════════════════════════════════════════╗
║  🛸 ORBIT - Flight Plan Generator                            ║
╚══════════════════════════════════════════════════════════════╝
`));

    console.log(`Feature: ${colors.secondary(feature)}`);
    console.log(`Plan ID: ${colors.secondary(planId)}`);
    console.log(`Depth: ${colors.secondary(String(this.options.depth))}`);
    console.log('');

    const template = this.generateTemplate(planId, feature);
    writeFileSync(planFile, template);

    if (this.options.dryRun) {
      console.log(colors.warning('[DRY RUN] Would generate plan'));
      return planId;
    }

    printSuccess(`Flight plan created: ${planFile}`);
    appendLog(`Created flight plan: ${planId} - ${feature}`);

    return planId;
  }

  private generateTemplate(planId: string, feature: string): string {
    const date = new Date().toISOString().split('T')[0];
    
    return `# 🛸 Flight Plan: ${feature}
# Generated: ${date}
# ID: ${planId}
# Status: DRAFT

## 🎯 Objective
${feature}

## 📋 Requirements
- [ ] Requirement 1
- [ ] Requirement 2

## 🏗️ Architecture Decisions
<!-- Key technical decisions and rationale -->

## 📦 Components
<!-- Major components/modules affected -->

## 🔄 Implementation Phases

### Phase 1: Foundation
- [ ] Task 1.1: Description
- [ ] Task 1.2: Description

### Phase 2: Core Implementation
- [ ] Task 2.1: Description
- [ ] Task 2.2: Description

### Phase 3: Integration & Testing
- [ ] Task 3.1: Description
- [ ] Task 3.2: Description

## 🧪 Testing Strategy
- Unit tests:
- Integration tests:
- E2E tests:

## 📚 Documentation Updates
- [ ] README updates
- [ ] API documentation
- [ ] User guides

## ⚠️ Risks & Mitigations
| Risk | Impact | Mitigation |
|------|--------|------------|
|      |        |            |

## 📊 Estimation
- Complexity: [LOW/MEDIUM/HIGH]
- Estimated phases: 3
- Estimated tasks: 6

## 🔗 Dependencies
- External:
- Internal:

---
*Generated by ORBIT Flight Plan*
`;
  }

  listPlans(): FlightPlan[] {
    if (!existsSync(PLANS_DIR)) return [];

    const files = readdirSync(PLANS_DIR).filter(f => f.endsWith('.md'));
    const plans: FlightPlan[] = [];

    for (const file of files) {
      const content = readFileSync(join(PLANS_DIR, file), 'utf-8');
      const id = file.replace('.md', '');
      
      const titleMatch = content.match(/^# 🛸 Flight Plan: (.+)$/m);
      const statusMatch = content.match(/^# Status: (.+)$/m);

      plans.push({
        id,
        title: titleMatch?.[1] || 'Unknown',
        objective: titleMatch?.[1] || '',
        status: (statusMatch?.[1]?.toLowerCase() || 'draft') as FlightPlan['status'],
        createdAt: '',
        phases: []
      });
    }

    return plans;
  }

  showPlan(planId: string): string | null {
    const planFile = join(PLANS_DIR, `${planId}.md`);
    if (!existsSync(planFile)) {
      printError(`Plan not found: ${planId}`);
      return null;
    }
    return readFileSync(planFile, 'utf-8');
  }

  async generateIssues(planId: string): Promise<boolean> {
    const planFile = join(PLANS_DIR, `${planId}.md`);
    
    if (!existsSync(planFile)) {
      printError(`Plan not found: ${planId}`);
      return false;
    }

    if (!commandExists('gh')) {
      printError('GitHub CLI (gh) not installed');
      return false;
    }

    console.log(colors.primary(`
╔══════════════════════════════════════════════════════════════╗
║  🐙 ORBIT - Issue Transmitter                                ║
╚══════════════════════════════════════════════════════════════╝
`));

    console.log(`Plan: ${colors.secondary(planId)}`);
    console.log('');

    if (this.options.dryRun) {
      console.log(colors.warning('[DRY RUN] Would generate issues'));
      return true;
    }

    const content = readFileSync(planFile, 'utf-8');
    const tasks = this.extractTasks(content);

    console.log(`Found ${tasks.length} tasks to create as issues`);

    for (const task of tasks) {
      const result = execQuiet(
        `gh issue create --title "[${planId}] ${task}" --body "From flight plan ${planId}" --label enhancement`
      );
      if (result) {
        printSuccess(`Created issue for: ${task}`);
      } else {
        printError(`Failed to create issue for: ${task}`);
      }
    }

    // Update plan status
    let updatedContent = content.replace(/^# Status: .+$/m, '# Status: ISSUES_CREATED');
    writeFileSync(planFile, updatedContent);

    printSuccess('Issues created');
    return true;
  }

  private extractTasks(content: string): string[] {
    const tasks: string[] = [];
    const regex = /^- \[ \] (.+)$/gm;
    let match;
    
    while ((match = regex.exec(content)) !== null) {
      // Skip generic placeholders
      if (!match[1].includes('Requirement') && !match[1].includes('Description')) {
        tasks.push(match[1]);
      }
    }
    
    return tasks;
  }
}

// CLI functions
export async function createFlightPlan(feature: string, options: FlightPlanOptions = {}): Promise<string> {
  const generator = new FlightPlanGenerator(options);
  return generator.createPlan(feature);
}

export function listFlightPlans(): void {
  const generator = new FlightPlanGenerator();
  const plans = generator.listPlans();

  console.log(colors.secondary('📋 Flight Plans'));
  console.log('');

  if (plans.length === 0) {
    console.log('  No plans yet. Create one with: orbit flight-plan new "feature"');
    return;
  }

  for (const plan of plans) {
    console.log(`  ${colors.secondary(plan.id)}: ${plan.title} [${plan.status}]`);
  }
}

export function showFlightPlan(planId: string): void {
  const generator = new FlightPlanGenerator();
  const content = generator.showPlan(planId);
  if (content) {
    console.log(content);
  }
}

export async function generateIssuesFromPlan(planId: string, options: FlightPlanOptions = {}): Promise<void> {
  const generator = new FlightPlanGenerator(options);
  await generator.generateIssues(planId);
}
